import { ProductOrder } from '@types';

export const dataMockup: ProductOrder = {
    totalAmount: 182000,
    items: [
        {
            id: 1,
            sap: "SAP_0001",
            name: "Bánh Bao Thịt Heo Trứng Cút",
            price: 18000,
            quantity: 1,
            unitQuantity: "Cái",
            image: "https://thophat.com/wp-content/uploads/2022/03/BB-Thit-Heo-1.jpg",
        },
        {
            id: 2,
            sap: "SAP_0002",
            name: "Bánh Bao Kim Sa",
            price: 19000,
            quantity: 1,
            unitQuantity: "Cái",
            image: "https://thophat.com/wp-content/uploads/2022/03/BB-Hoang-Kim-1.jpg",
        },
        {
            id: 3,
            sap: "SAP_0003",
            name: "Bánh Bao Xá Xíu",
            price: 17000,
            quantity: 1,
            unitQuantity: "Cái",
            image: "https://thophat.com/wp-content/uploads/2022/03/BB-Xa-Xiu-1.jpg",
        },
        {
            id: 4,
            sap: "SAP_0004",
            name: "Bánh Bao Gà Nấm",
            price: 18000,
            quantity: 1,
            unitQuantity: "Cái",
            image: "https://thophat.com/wp-content/uploads/2022/03/BÁNH-BAO-TRÒN-TÍM-1.jpg",
        },
        {
            id: 5,
            sap: "SAP_0005",
            name: "Bánh Bao Chay",
            price: 16000,
            quantity: 1,
            unitQuantity: "Cái",
            image: "https://thophat.com/wp-content/uploads/2022/03/BB-Chay-400g-1.jpg",
        },
        {
            id: 6,
            sap: "SAP_0006",
            name: "Há Cảo Thịt Tôm",
            price: 19000,
            quantity: 1,
            unitQuantity: "Phần",
            image: "https://thophat.com/wp-content/uploads/2022/03/BB-Thit-Heo-Trung-Muoi-170g-1.jpg",
        },
        {
            id: 7,
            sap: "SAP_0007",
            name: "Xíu Mại Thịt",
            price: 17000,
            quantity: 1,
            unitQuantity: "Phần",
            image: "https://thophat.com/wp-content/uploads/2022/03/BB-Thit-Heo-Trung-Muoi-170g-1.jpg",
        },
        {
            id: 8,
            sap: "SAP_0008",
            name: "Bánh Giò",
            price: 18000,
            quantity: 1,
            unitQuantity: "Cái",
            image: "https://thophat.com/wp-content/uploads/2022/03/BB-Thit-Heo-Trung-Muoi-170g-1.jpg",
        },
        {
            id: 9,
            sap: "SAP_0009",
            name: "Bánh Bao Nướng",
            price: 17000,
            quantity: 1,
            unitQuantity: "Cái",
            image: "https://thophat.com/wp-content/uploads/2022/03/BB-Thit-Heo-Trung-Muoi-170g-1.jpg",
        },
        {
            id: 10,
            sap: "SAP_0010",
            name: "Bánh Bao Phô Mai",
            price: 17000,
            quantity: 1,
            unitQuantity: "Cái",
            image: "https://thophat.com/wp-content/uploads/2022/03/Xoi-Ga-1.jpg",
        },
    ],
};
